### ISSUE TITLE
does it work?

### ISSUE THREAD

**Issue by IGNRexI** [L-Leite/libuncso2#1]
does it work?
I want to archive several files

**Comment by lateleite** [comment]
It does.

I am setting up a new release of UnCSO2 that decrypts files correctly, is faster and better looking. It will also support the extraction of Titanfall Online's files.

It won't support repacking PKG files though.

I will publish it at the [UnCSO2 repository](https://github.com/Ochii/UnCSO2) very soon

**Comment by IGNRexI** [comment]
Is it possible to package the .pkg file?

**Comment by lateleite** [comment]
> Is it possible to package the .pkg file?

No, and I don't think I will ever implement that feature
